---
title: "Combining predictors"
output: html_notebook
---

###Create traning, test and validation sets

```{r}
library(ISLR); data("Wage"); library(ggplot2); library(caret)
Wage <- subset(Wage, select = -c(logwage))
```

###Create a building data set and validation set (3 data sets)
```{r}
inBuild <- createDataPartition(y=Wage$wage, p=0.7, list = FALSE)
validation <- Wage[-inBuild,]; buildData <- Wage[inBuild,]
inTrain <- createDataPartition(y=buildData$wage, p=0.7, list = FALSE)
training <- buildData[inTrain,]; testing <- buildData[-inTrain,]
```

###Create training, test and validation sets
```{r}
dim(training)
```


```{r}
dim(testing)
```

```{r}
dim(validation)
```

###Build two different models
```{r}
mod1 <- train(wage ~., method = "glm", data = training)
mod2 <- train(wage ~., method = "rf", data = training, trControl = trainControl(method = "cv"), number = 3)
```

###Predict on testing set
```{r}
pred1 <- predict(mod1, testing); pred2 <- predict(mod2, testing)
qplot(pred1, pred2, colour=wage, data = testing)
```

###Fit a model that combines predictors
```{r}
library(mgcv); library(nlme)
predDF <- data.frame(pred1, pred2, wage <- testing$wage)
combModFit <- train(wage ~., method = "gam", data = predDF)
combPred <- predict(combModFit, predDF)
```

###Testing errors
```{r}
sqrt(sum((pred1-testing$wage)^2))
```

```{r}
sqrt(sum((pred2-testing$wage)^2))
```

```{r}
sqrt(sum((combPred-testing$wage)^2))
```

###Predict on validation data set
```{r}
library(randomForest)
pred1V <- predict(mod1, validation); pred2V <- predict(mod2, validation)
predVDF <- data.frame(pred1=pred1V, pred2=pred2V)
combPredV <- predict(combModFit, predVDF)
```

###Evaluate on validation
```{r}
sqrt(sum((pred1V-validation$wage)^2))
```

```{r}
sqrt(sum(pred2V-validation$wage)^2)
```

```{r}
sqrt(sum((combPredV-validation$wage)^2))
```
